config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: {sessions: 'sessions'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "public#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/oferty", to: "oferty#index"
  get "/branzas/add", to: "branzas#new"
  get "/branzas", to: "branzas#index"
  get "/firma", to: "firma#index"
  get "/firma/add", to: "firma#new"
  get "/oferty/add", to: "oferty#new"
  get "/stanowiska", to: "stanowiska#index"
  get "/stanowiska/add", to: "stanowiska#new"
  get '/odpowiedz/:id', to: 'odpowiedzias#respond', as: 'odpowiedz'
  post "/odpowiedz/:id", to: 'odpowiedzias#create'
  get "/uzytkownicy", to: "uzytkownicy#index"
  get "/oferty/twoje" , to: "oferty#twoje"
  get "/odpowiedzias/firma", to: "odpowiedzias#firma"
  get "/odpowiedzias/szczegoly/:id", to: "odpowiedzias#szczegoly" ,as: 'odpowiedz_index'
  post "/odpowiedzias", to: "odpowiedzias#create"

  resources :branzas
  resources :oferty
  resources :stanowiska
  resources :firma
  resources :odpowiedzias
  resources :uzytkownicy


  match "*unmatched_route", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  # Defines the root path route ("/")
  # root "posts#index"

end

app/controllers/stanowiska_controller.rb
class StanowiskaController < ApplicationController


  #Akcja wyswietlająca wszystkie stanowiska
  def index
    @Stanowisko= Stanowisko.all
  end
  #Akcja wyswietlająca formularz dodawania stanowiska
  def new
    @Stanowisko=Stanowisko.new
  end

  #Akcja ktora tworzy nowe stanowisko z danych z formularza
  def create
    @Stanowisko=Stanowisko.new(stanowisko_params)
    if @Stanowisko.save
      redirect_to stanowiska_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  #Metoda zabezpieczająca przesyłane parametry formularza
  private
  def stanowisko_params
    params.require(:stanowisko).permit(:nazwa)
  end

end

app/views/stanowiska/index.html.erb
<h1 style="text-align: center">Stanowiska</h1>
<br>
<div style="display: flex;justify-content: center;align-items: center;
  height: 20vh;">

<ul>
  <% @Stanowisko.each do |stano| %>
    <li>
      <%= stano.nazwa %>
    </li>
  <% end %>


</ul>
</div>

app/views/stanowiska/new.html.erb
<h1 style="text-align: center">Stworz Stanowisko</h1>
<div style="display: flex;justify-content: center;align-items: center;
  height: 20vh;">
<%= form_with model: @Stanowisko, url: stanowiska_path do |form| %>
  <div>
    <%=form.label :nazwa %>
    <br>
    <br>
    <%= form.text_field :nazwa %>
  </div>
  <div>
    <br>
    <br>
    <%=form.submit %>
  </div>
<% end %>
</div>