config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: {sessions: 'sessions'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "public#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/oferty", to: "oferty#index"
  get "/branzas/add", to: "branzas#new"
  get "/branzas", to: "branzas#index"
  get "/firma", to: "firma#index"
  get "/firma/add", to: "firma#new"
  get "/oferty/add", to: "oferty#new"
  get "/stanowiska", to: "stanowiska#index"
  get "/stanowiska/add", to: "stanowiska#new"
  get '/odpowiedz/:id', to: 'odpowiedzias#respond', as: 'odpowiedz'
  post "/odpowiedz/:id", to: 'odpowiedzias#create'
  get "/uzytkownicy", to: "uzytkownicy#index"
  get "/oferty/twoje" , to: "oferty#twoje"
  get "/odpowiedzias/firma", to: "odpowiedzias#firma"
  get "/odpowiedzias/szczegoly/:id", to: "odpowiedzias#szczegoly" ,as: 'odpowiedz_index'
  post "/odpowiedzias", to: "odpowiedzias#create"

  resources :branzas
  resources :oferty
  resources :stanowiska
  resources :firma
  resources :odpowiedzias
  resources :uzytkownicy


  match "*unmatched_route", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  # Defines the root path route ("/")
  # root "posts#index"

end

app/controllers/oferty_controller.rb
class OfertyController < ApplicationController

  before_action :authenticate_user!, only: [:new]
  #Akcja wyswietlająca oferty
  #@oferty- zawiera oferty wszystkie lub przefiltrowane przez branze
  def index
    if params[:branza_id].present?
      @oferty = Ofertum.where(id_branzy: params[:branza_id]).order(created_at: :desc)
    else
      @oferty = Ofertum.all.order(created_at: :desc)
    end
    @branze = Branza.all
    @firma = Firma.all
    @stanowisko = Stanowisko.all
  end


  #Akcja wyswietlająca wszystkie oferty danego uzytkownika z uwzględnieniem że moze miec kilka firm
  def twoje
    Rails.logger.info"Uzytkownik wyswietla swoje oferty"
    @firmy = Firma.where(user_id: current_user.id)

    firma_ids = @firmy.pluck(:id)

    @oferty = Ofertum.where(id_firmy: firma_ids)
    @branze = Branza.all
    @firma = Firma.all
    @stanowisko = Stanowisko.all

  end

  # Akcja wyswietlająca formularz tworzenia oferty
  def new
    @oferty = Ofertum.new
    @branze = Branza.all
    @firma = Firma.all
    @stanowisko = Stanowisko.all
  end


  # Akcja tworzaca nową oferte
  def create

    @oferty = Ofertum.new(ofertum_params)
    @branze = Branza.all
    @firma = Firma.all
    @stanowisko = Stanowisko.all
    @checkBox1=params[:my_checkbox1]
    @checkBox2=params[:my_checkbox2]
    @checkBox3=params[:my_checkbox3]
    @checkBox4=params[:my_checkbox4]
    @checkBox5=params[:my_checkbox5]
    @checkBox6=params[:my_checkbox6]
    #przetwarza dane z chechboxow i konwertuje na zapis ,,binarny"
    puts @checkBox1
    binary_value = ''
    (1..6).each do |i|
      checkbox_param = "my_checkbox#{i}".to_sym
      puts checkbox_param
      if params[checkbox_param] == '1'
        puts "True"
        binary_value += '1'
      else
        puts "False"
        binary_value += '0'
      end
    end

    @oferty.rodzaj = binary_value

    puts "Binary value: #{binary_value}"

    if @oferty.save
      redirect_to oferty_url
    else
      render :new, status: :unprocessable_entity
    end
  end
  # Metoda zabezpieczająca przesyłane parametry formularza
  # oczekujemy klucza-ofertum ktory jest nazwa modelu
  # okreslamy jakie parametry chcemy uzyskac
  private
  def ofertum_params
    params.require(:ofertum).permit(:tytul, :id_branzy, :id_stanowiska, :id_firmy)
  end

end

app/views/oferty/index.html.erb
<div align="center" style="justify-content: center;align-items: center;">
  <h1>Oferty</h1>
  <h3>
    Filtruj po branży
  </h3>
<%= form_tag oferty_path, method: :get do %>
  <%= select_tag :branza_id, options_from_collection_for_select(@branze, :id, :nazwa) %>
  <%= submit_tag "Filtruj" %>
<% end %>
</div>

<ol class="no-style">
  <% @oferty.each do |oferta| %>
    <hr class="dotted-hr">
  <li>
    <br><br>
    <div align="center">
    <strong>Tytuł:</strong> <%= oferta.tytul %>
    </div>
    <div>
                <div align="left" style="float:left ; width: 20%; height: 120px" >

                       <% if Firma.find(oferta.id_firmy).image.present? %>
                         <p>
                       <%= image_tag Firma.find(oferta.id_firmy).image.url %>
                         </p>
                        <% end %>
               </div>
              <br>
              <div align="center" style="float:left ; width: 40%; height: 120px">
                <p><%= oferta.id %></p>
                      <strong>Firma:</strong> <%= Firma.find(oferta.id_firmy).nazwa %>
                      <br>
                      <strong>Stanowisko:</strong> <%= Stanowisko.find(oferta.id_stanowiska).nazwa %>
                      <br>
                      <strong>Branża:</strong> <%= Branza.find(oferta.id_branzy).nazwa %>
                      <strong>Rodzaj:</strong> <%= oferta.rodzaj %>
              </div>
              <br>
              <div align="center" style="float: left; width:40%;">
                        <a  href="<%= odpowiedz_path(oferta.id) %>" class="btn square-btn">Odpowiedz na oferte</a>
              </div>
    </div>
  </li>
  <% end %>


</ol>

app/views/oferty/new.html.erb
<h1 style="text-align: center">Stworz Oferte</h1>
<hr class="dotted-hr">
<br>
<br>
    <div >
  <%= form_with model: @oferty, url: oferty_path do |form| %>
                <div align=center style="float:left ;width: 50%">
                  <h3 style="text-align: center"> Podstawowe dane o ofercie  </h3>
                                             <div>
                                    <%=form.label :tytul %>
                                      <br>
                                      <%= form.text_field :tytul %>
                                            </div>
                                            <br>
                                            <div>
                                      <%=form.label :Branże %>
                                      <br>
                                      <%=form.collection_select :id_branzy , @branze, :id, :nazwa %>
                                             </div>
                                             <br>
                                            <div>
                                      <%=form.label :Stanowisko %>
                                      <br>
                                      <%=form.collection_select :id_stanowiska , @stanowisko, :id, :nazwa %>
                                             </div>
                                    <br>
                                              <div>
                                      <%=form.label :Firma %>
                                      <br>
                                      <%=form.collection_select :id_firmy , @firma, :id, :nazwa %>

                                              </div>




                </div>
                <br>
                <div align =center style="float:left; width:50%">
                                      <h3 style="text-align: center"> Wybierz wymagane pola  </h3>
                                            <div>
                                      <%=form.label :Wiek %>
                                      <%= check_box_tag 'my_checkbox1' %>
                                            </div>
                                      <br>
                                            <div>
                                      <%=form.label :Wykształcenie %>
                                      <%= check_box_tag 'my_checkbox2' %>
                                            </div>
                                      <br>
                                            <div>
                                      <%=form.label :Miejscezamieszkania %>
                                      <%= check_box_tag 'my_checkbox3' %>
                                            </div>
                                      <br>
                                            <div>
                                      <%=form.label :Staż %>
                                      <%= check_box_tag 'my_checkbox4' %>
                                            </div>
                                      <br>
                                            <div>
                                      <%=form.label :Staż %>
                                      <%= check_box_tag 'my_checkbox5' %>
                                            </div>
                                      <%= check_box_tag 'my_checkbox6' %>

                 </div>
                 <div align="center" >
                                      <br>
                                      <br>
                                      <%=form.submit "Dodaj oferte",class:"btn square-btn" %>
                 </div>
                <% end %>
      </div>

app/views/oferty/twoje.html.erb
<div align="center" style="justify-content: center;align-items: center;">
  <h1>Oferty</h1>

  <h3>
    Filtruj po branży
  </h3>
  <%= form_tag oferty_path, method: :get do %>
    <%= select_tag :branza_id, options_from_collection_for_select(@branze, :id, :nazwa) %>
    <%= submit_tag "Filtruj" %>
  <% end %>
</div>

<ol class="no-style">
  <% @oferty.each do |oferta| %>
    <hr class="dotted-hr">
    <li>
      <br><br>
      <div align="center">
        <strong>Tytuł:</strong> <%= oferta.tytul %>
      </div>
      <div>
        <br>
        <div align="center" style="float:left ; width: 50%; height: 120px">
          <p><%= oferta.id %></p>
          <strong>Firma:</strong> <%= Firma.find(oferta.id_firmy).nazwa %>
          <br>
          <strong>Stanowisko:</strong> <%= Stanowisko.find(oferta.id_stanowiska).nazwa %>
          <br>
          <strong>Branża:</strong> <%= Branza.find(oferta.id_branzy).nazwa %>
          <strong>Rodzaj:</strong> <%= oferta.rodzaj %>
        </div>
        <br>
        <div align="center" style="float: left; width:50%;">
          <a  href="<%= odpowiedz_path(oferta.id) %>" class="btn square-btn">Odpowiedz na oferte</a>
        </div>
      </div>
    </li>
  <% end %>


</ol>