config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: {sessions: 'sessions'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "public#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/oferty", to: "oferty#index"
  get "/branzas/add", to: "branzas#new"
  get "/branzas", to: "branzas#index"
  get "/firma", to: "firma#index"
  get "/firma/add", to: "firma#new"
  get "/oferty/add", to: "oferty#new"
  get "/stanowiska", to: "stanowiska#index"
  get "/stanowiska/add", to: "stanowiska#new"
  get '/odpowiedz/:id', to: 'odpowiedzias#respond', as: 'odpowiedz'
  post "/odpowiedz/:id", to: 'odpowiedzias#create'
  get "/uzytkownicy", to: "uzytkownicy#index"
  get "/oferty/twoje" , to: "oferty#twoje"
  get "/odpowiedzias/firma", to: "odpowiedzias#firma"
  get "/odpowiedzias/szczegoly/:id", to: "odpowiedzias#szczegoly" ,as: 'odpowiedz_index'
  post "/odpowiedzias", to: "odpowiedzias#create"

  resources :branzas
  resources :oferty
  resources :stanowiska
  resources :firma
  resources :odpowiedzias
  resources :uzytkownicy


  match "*unmatched_route", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  # Defines the root path route ("/")
  # root "posts#index"

end

app/controllers/odpowiedzias_controller.rb
class OdpowiedziasController < ApplicationController

  def index
    @odpowiedzi = Odpowiedz.all

  end
  #Akcja wyswietlajaca wszystkie odpowiedzi dla danej firmy/firm
  def firma
    @firma = Firma.where(user_id: current_user.id)
    firma_id = @firma.pluck(:id)
    oferty  = Ofertum.where(id_firmy: firma_id)
    @odpowiedzi = []

    oferty.each do |oferta|

      @odpowiedzi += Odpowiedz.where(id_oferty: oferta.id).order(created_at: :desc)

    end

    #Akcja wyswietlajaca szczegoly danej odpowiedzi
    def szczegoly
      @odpowiedz=Odpowiedz.find(params[:id])
    end

  end

  #Akcja wyswietla formularz odpowiedzi na dana oferte
    def respond
      @oferta = Ofertum.find(params[:id])
      @odpowiedz = Odpowiedz.new
      @rodzaj=@oferta.rodzaj

    end
  #Akcja tworzy odpowiedz na podstawie danych z formularza
    def create
      @oferta = Ofertum.find(params[:oferta_id])
        @odpowiedz = Odpowiedz.new(odpoweidz_params)
      @odpowiedz.id_oferty = @oferta.id

      if @odpowiedz.save
        redirect_to "/oferty", notice: 'Odpowiedź została pomyślnie zapisana.'
      else
        Rails.logger.info("Nie udało sie zapisać odpowiedzi")
        render :respond
      end
    end
  #Metoda zabezpieczajaca przesylane parametry formularza
    private
    def odpoweidz_params
      params.require(:odpowiedz).permit(:wiek, :imie, :nazwisko, :miejsce_zamieszaknia, :staz , :rodzaj_wyksztalcenia,:nr_tel,:email)
    end
  end

app/views/odpowiedzias/firma.html.erb
<div align="center" style="justify-content: center;align-items: center;">
  <h1>Odpowiedzi</h1>


</div>
<hr class="dotted-hr">
<% if @odpowiedzi.any? %>
  <div class="table-container">
  <table class="moja-tabela">
    <thead>
    <tr>
      <th>Firma</th>
      <th>Oferta</th>
      <th>Imię</th>
      <th>Nazwisko</th>




    </tr>
    </thead>
    <tbody>
    <% @odpowiedzi.each do |odpowiedz| %>

      <tr>
        <td><%= Firma.find((Ofertum.find(odpowiedz.id_oferty).id_firmy)).nazwa %></td>
        <td><%= Ofertum.find(odpowiedz.id_oferty).tytul %></td>
        <td><%= odpowiedz.imie %></td>
        <td><%= odpowiedz.nazwisko %></td>

        <td>  <div align="center" style="float: left; width:30%;">
          <a  href="<%= odpowiedz_index_path(odpowiedz.id) %>" class="btn square-btn">szczegoly</a>
        </div></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Brak odpowiedzi do wyświetlenia.</p>
<% end %>
</div>

app/views/odpowiedzias/respond.html.erb
<h1 align="center">Formularz odpowiedzi</h1>
<hr class="dotted-hr">
<div>
<%= form_with model: @odpowiedz, url: odpowiedzias_path(oferta_id: @oferta.id) do |form| %>
  <div align="center"  style="float:left ; width: 40%" >


                        <div align="center" style="float:left ; width: 50%">
                          <br>
                          <br>
                          <br>
                          <% if Firma.find(@oferta.id_firmy).image.present? %>
                            <p>
                              <%= image_tag Firma.find(@oferta.id_firmy).image.url %>
                            </p>
                          <% end %>
                         </div>

                       <div align="center" style="float:left ; width: 50%">
                         <p style="font-size: 24px ;font-weight: bold;">Informacje o ogłoszeniu</p>
                              <p>Tytuł oferty: <%= @oferta.tytul %></p>
                              <p>Stanowisko: <%= Stanowisko.find(@oferta.id_stanowiska).nazwa %></p>
                              <p>Firma: <%= Firma.find(@oferta.id_firmy).nazwa %></p>
                              <p>Branża: <%= Branza.find(@oferta.id_branzy).nazwa %></p>
                              <p>Rodzaj: <%= @oferta.rodzaj %></p>
                      </div>

  </div>

    <div align="center" style="float:left ; width: 29%">
      <p style="font-size: 24px ;font-weight: bold;">Podstawowe informacje</p>
      <div class="blue-box">
        <br>

                              <%=form.label :Imię %>
                              <br>
                              <%= form.text_field :imie %>
                              <br>
                              <%=form.label :Nazwisko %>
                              <br>
                              <%= form.text_field :nazwisko %>
                              <br>
                              <%=form.label :Numer_Kontaktowy %>
                              <br>
                              <%= form.text_field :nr_tel %>
                              <br>
                              <%=form.label :Email %>
                              <br>
                              <%= form.text_field :email%>

        <br>
        <br>
      </div>
    </div>

    <div align="center" style="float:left ; width: 29%">
      <p style="font-size: 24px ;font-weight: bold;">Dodatkowe pola do wypełnienia</p>
      <div class="blue-box">
        <br>

                                    <% if @rodzaj.present? && @rodzaj[0] == "1" %>
                                                    <div >
                                                                  <%=form.label :Wiek0 %>
                                                                  <br>
                                                                  <%= form.text_field :wiek %>
                                                    </div>
                                    <% end %>

                                    <% if @rodzaj.present? && @rodzaj[1] == "1" %>
                                                    <div >
                                                                  <%=form.label :Wykształcenie1 %>
                                                                  <br>
                                                                  <%= form.text_field :rodzaj_wyksztalcenia %>

                                                    </div>
                                    <% end %>
                                    <% if @rodzaj.present? && @rodzaj[2] == "1" %>
                                                    <div >
                                                                  <%=form.label :MiejsceZamieszkania2 %>
                                                                  <br>
                                                                  <%= form.text_field :miejsce_zamieszkania %>

                                                    </div>
                                    <% end %>
                                    <% if @rodzaj.present? && @rodzaj[3] == "1" %>
                                                    <div >
                                                                  <%=form.label :Staz3 %>
                                                                  <br>
                                                                  <%= check_box_tag :staz %>

                                                    </div>
                                    <% end %>


        <br>
        <br>
      </div>
</div>

    <div></div>
    <div  style="clear:both"></div>
  <div align="center"  >

    <%=form.submit "Wyślij" ,class:"btn square-btn" %>
  </div>
<% end %>
</div>

app/views/odpowiedzias/szczegoly.html.erb
<div align="center" style="justify-content: center;align-items: center;">
  <h1>Szczegóły </h1>


</div>
<hr class="dotted-hr">
<% if @odpowiedz!=nil %>

  <p style="text-align: center;font-size:20px;"><%= Ofertum.find(@odpowiedz.id_oferty).tytul %></p>
  <div >
  <table class="moja-tabela">
    <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Wiek</th>
      <th>Numer Kontaktowy</th>
      <th>Miejsce zamieszkania</th>
      <th>Staż</th>
      <th>Rodzaj wykształcenia</th>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>

    <hr>
    <br>
      <tr>

        <td><%= @odpowiedz.imie %></td>
        <td><%= @odpowiedz.nazwisko %></td>

        <td><%= @odpowiedz.wiek %></td>
        <th><%= @odpowiedz.nr_tel %></th>
        <td><%= @odpowiedz.miejsce_zamieszaknia unless @odpowiedz.miejsce_zamieszaknia.nil? %></td>
        <td><%= @odpowiedz.staz %></td>
        <td><%= @odpowiedz.rodzaj_wyksztalcenia %></td>
        <td><%= @odpowiedz.email %></td>
      </tr>

    </tbody>
  </table>
  </div>
<% else %>
  <p>Brak odpowiedzi do wyświetlenia.</p>
<% end %>