config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, controllers: {sessions: 'sessions'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "public#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/oferty", to: "oferty#index"
  get "/branzas/add", to: "branzas#new"
  get "/branzas", to: "branzas#index"
  get "/firma", to: "firma#index"
  get "/firma/add", to: "firma#new"
  get "/oferty/add", to: "oferty#new"
  get "/stanowiska", to: "stanowiska#index"
  get "/stanowiska/add", to: "stanowiska#new"
  get '/odpowiedz/:id', to: 'odpowiedzias#respond', as: 'odpowiedz'
  post "/odpowiedz/:id", to: 'odpowiedzias#create'
  get "/uzytkownicy", to: "uzytkownicy#index"
  get "/oferty/twoje" , to: "oferty#twoje"
  get "/odpowiedzias/firma", to: "odpowiedzias#firma"
  get "/odpowiedzias/szczegoly/:id", to: "odpowiedzias#szczegoly" ,as: 'odpowiedz_index'
  post "/odpowiedzias", to: "odpowiedzias#create"

  resources :branzas
  resources :oferty
  resources :stanowiska
  resources :firma
  resources :odpowiedzias
  resources :uzytkownicy


  match "*unmatched_route", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  # Defines the root path route ("/")
  # root "posts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projekt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
   <!-- <link rel="stylesheet" href="style.css"> -->
  </head>

  <body>

  <header>
                  <div style="float:left;width: calc(100% / 3);">
                            <p>image tu ma byc</p>
                  </div>
                  <div align="center" style="float:left;width: calc(100% / 3);">
                            <h1 class="stylish-text size_portal">PORTAL PRACY</h1>
                  </div>
                  <div align="center" class="btn_2">
                            <% if  user_signed_in? %>
                              <p>Zalogowany jako <%= current_user.email %></p>
                              <div class="btn">
                              <%= link_to "Wyloguj się", destroy_user_session_path, data: { turbo_method: :delete } %>
                              </div>
                            <% else %>
                              <div class="btn">
                              <%= link_to "Zaloguj się", new_user_session_path %>
                              </div>
                            <% end %>
                            <% if user_signed_in? && current_user.admin? %>
                              <%= link_to 'Użytkownicy', uzytkownicy_path %>
                            <% end %>
                  </div>
                  <div style="clear: both">

                  </div>
                  <div align="center" style="float: left;width: calc(100% / 3); background-color: skyblue;">
                      <h1 class="stylish-text" >Branże</h1>

                                            <% if user_signed_in? && current_user.admin? %>
                                              <a href="/branzas/add" class="btn large-btn ">Dodaj branze</a>
                      <br>
                                            <% end %>


                                              <a href="/branzas" class="btn large-btn ">Obejrzyj branze</a>

                  </div>
                  <div align="center" style="float: left;width: calc(100% / 3);background-color: skyblue;">
                                              <h1 class="stylish-text">Firmy</h1>
                                              <% if user_signed_in? %>
                                              <a href="/firma/add" class="btn large-btn ">Dodaj firme</a>
                                              <% end %>
                                              <br>
                                              <% if user_signed_in? %>
                                                <a href="/odpowiedzias/firma" class="btn large-btn ">Zobacz Odpowiedzi</a>
                                              <% end %>
                                              <a href="/firma" class="btn large-btn ">Przejrzyj firmy</a>

                  </div>
                  <div align="center"  style="float: left;width: calc(100% / 3);background-color: skyblue;align:center ;">
                                              <h1 class="stylish-text">Oferty</h1>
                                              <% if user_signed_in? %>
                                              <a href="/oferty/add" class="btn large-btn ">Dodaj oferte</a>
                                              <% end %>
                                              <% if user_signed_in? %>
                                                <a href="/oferty/twoje" class="btn large-btn ">Twoje oferty</a>
                                              <% end %>
                                              <br>

                                              <a href="/oferty" class="btn large-btn ">Przejrzyj oferty</a>

                  </div>

  </header>

  </body>
  <%= yield %>
</html>